# -*- coding: utf-8 -*-
"""Streamlit working tuts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O-3NLDKVRBJV6GUnQDN3bROqTwhxiIZY
"""

! pip install streamlit -q

!wget -q -O- ipv4.icanhazip.com

! pip install pandas openpyxl

! pip install python-docx
! pip install docx2pdf

! pip install matplotlib

! streamlit run new.py & npx localtunnel --port 8501